server:
  port: 8762
spring:
  application:
    name: zuul-server
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
  serviceurl:
    defaultzone: http://192.168.101.74:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: routes,filters
logging:
  level:
   root: INFO
  file: /var/zuul-server.log