spring:
  application:
    name: vch-service
server:
  port: 8180
eureka:
  client:
     service-url:
          defaultZone: "http://192.168.101.98:8761/eureka/"
  instance:
    preferIpAddress: true
  healthcheck:
    enabled: true
db:
  driver: org.postgresql.Driver
  url: jdbc:postgresql://192.168.101.58:5432/Production
  username: slonik
  password: psina228
hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  show_sql: true
  current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
  batch.size: 50
  jdbc:
    lob:
      non_contextual_creation: true
entitymanager:
  packagesToScan: project.db.model