ftp:
  url: ftp.vniiftri.ru
  remotedirectory: Atomic_Time/SU/links/GNSS/UTC(SU)-GNSS/CGGTTS
  localdirectory: ftp
  rirtdirectory: \\192.168.101.141\6rrt\BIPM
  login: anonymous
  password: anonymous
  port: 21
db:
  driver: org.postgresql.Driver
  url: jdbc:postgresql://192.168.101.58:5432/Production
  username: slonik
  password: psina228
hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  show_sql: true
  current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
  batch.size: 1
  jdbc:
    lob:
      non_contextual_creation: true
entitymanager:
  packagesToScan: project.hibernate.model