server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-Registry: false
  server:
    enableSelfPreservation: true
logging:
  level:
   root: INFO
  file: /var/eureka-server.log
db:
  driver: org.postgresql.Driver
  url: jdbc:postgresql://192.168.101.58:5432/Production
  username: slonik
  password: psina228
hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  show_sql: true
  current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
  batch.size: 25
  jdbc:
    lob:
      non_contextual_creation: true
entitymanager:
  packagesToScan: project.hibernate.model