spring:
  application:
    name: real-time-calculation
server:
  port: 8777
eureka:
  client:
     service-url:
          defaultZone: "http://127.0.0.1:8761/eureka/"
  instance:
    preferIpAddress: true
  healthcheck:
    enabled: true
db:
  driver: org.postgresql.Driver
  url: jdbc:postgresql://192.168.101.58:5432/Production
  username: slonik
  password: psina228
hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  show_sql: false
  current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
  batch.size: 50
  jdbc:
    lob:
      non_contextual_creation: true
entitymanager:
  packagesToScan: client.hibernate.model